"""
exp_53_noise_sweep.py
=====================
Experiment 5.3 — Noise tolerance threshold.

Gradually increases training noise level and records F1 per method.
Answers "how noisy is too noisy?" with a principled threshold rather
than just two snapshots (Experiments 5.1 and 5.2).

Unlike other experiments, training data MUST be generated at each noise
level — that is the experiment. The test set and negatives are loaded
from disk (generated by generate_all_data.py) so they are identical
across all experiments.

Requires: run generate_all_data.py first.

Output (timestamped folder under Graphs/Metrics_noisy_sweep/):
  config.txt          — all parameters used in this run
  results.json        — all metrics per noise level per method
  f1_vs_noise.png
  recall_vs_noise.png
  precision_vs_noise.png
"""

import json
import sys
from collections import Counter
from datetime import datetime
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from Generate_data import load_all_data, CONFIG
from Generators import generate_trace_set, NEG_MODE_NAMES
from Pipeline import run_pipeline


# =============================================================================
# CONFIG
# =============================================================================

N_TRAIN = CONFIG["n_train"]

NOISE_LEVELS = [0.02, 0.05, 0.1, 0.15, 0.2, 0.25]

F1_THRESHOLD = 0.7

TAG_K = 4

METHODS = [
    ("naive",   {"bins": 5}),
    ("sax",     {"w": 144, "bins": 5}),
    ("persist", {"bins": 6}),
]

METHOD_COLORS = {
    "naive":   "steelblue",
    "sax":     "darkorange",
    "persist": "seagreen",
}


# =============================================================================
# CONFIG FILE
# =============================================================================

def save_config(out_dir, data):
    """
    Save a plain-text summary of all configuration parameters used in this run.
    """
    lines = [
        "=" * 55,
        "Run configuration -- Noise Sweep",
        "=" * 55,
        "",
        f"Timestamp      : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"TAG k-future   : {TAG_K}",
        f"F1 threshold   : {F1_THRESHOLD}",
        "",
        "--- Noise levels swept ---",
        f"  {NOISE_LEVELS}",
        f"  Clean baseline: {CONFIG['clean']['noise_std']}",
        f"  Noisy baseline: {CONFIG['noisy']['noise_std']}",
        "",
        "--- Base training parameters (noise_std overridden per level) ---",
        f"  base_temp     : {CONFIG['clean']['base_temp']}",
        f"  amplitude     : {CONFIG['clean']['amplitude']}",
        f"  base_temp_std : {CONFIG['clean']['base_temp_std']}",
        f"  amplitude_std : {CONFIG['clean']['amplitude_std']}",
        f"  phase_std_h   : {CONFIG['clean']['phase_std_h']}",
        f"  seed          : {CONFIG['seed_clean']}",
        "",
        "--- Methods ---",
        ]

    for method, params in METHODS:
        param_str = ", ".join(f"{k}={v}" for k, v in params.items())
        lines.append(f"  {method:8s}: {param_str}")

    lines += [
        "",
        "--- Dataset sizes ---",
        f"  train per level : {N_TRAIN} traces (regenerated at each noise level)",
        f"  test positives  : {len(data['clean_test'])} traces (fixed, from disk)",
        f"  negatives       : {len(data['neg_traces'])} traces (fixed, from disk)",
        "",
        "--- Negative modes ---",
    ]

    mode_counts = Counter(data["neg_modes"])
    for mode_int, count in sorted(mode_counts.items()):
        lines.append(f"  {NEG_MODE_NAMES[mode_int]:10s}: {count} traces")

    lines += [
        "",
        "--- Output folder ---",
        f"  {out_dir}",
        "",
        "=" * 55,
        ]

    config_path = out_dir / "config.txt"
    with open(config_path, "w") as f:
        f.write("\n".join(lines))
    print(f"  Saved: {config_path}")


# =============================================================================
# PLOTTING
# =============================================================================

def _plot_metric(results_by_method, noise_levels, metric, ylabel, title,
                 threshold, out_path):
    fig, ax = plt.subplots(figsize=(10, 5))

    for method, vals in results_by_method.items():
        ax.plot(noise_levels, vals[metric],
                marker="o", linewidth=2, markersize=5,
                color=METHOD_COLORS.get(method, "gray"),
                label=method)

    ax.axhline(threshold, color="red", linewidth=1.2, linestyle="--",
               label=f"Threshold = {threshold}")

    clean_noise = CONFIG["clean"]["noise_std"]
    noisy_noise = CONFIG["noisy"]["noise_std"]
    for level, label_text in [(clean_noise, "clean"),
                              (noisy_noise, "noisy")]:
        ax.axvline(level, color="gray", linewidth=1.0, linestyle=":",
                   alpha=0.7)
        ax.text(level, 0.02, label_text, rotation=90,
                fontsize=7, color="gray", va="bottom", ha="right")

    ax.set_xlabel("Training noise std (C)")
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.legend()
    ax.grid(True, linestyle="--", alpha=0.5)
    ax.set_ylim(0, 1.05)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {out_path}")


def _find_threshold_crossings(noise_levels, f1_vals, threshold):
    crossing_at = None
    last_above  = None
    for n, f in zip(noise_levels, f1_vals):
        if f >= threshold:
            last_above = n
        elif crossing_at is None:
            crossing_at = n
    return crossing_at, last_above


# =============================================================================
# MAIN
# =============================================================================

if __name__ == "__main__":
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    out_dir   = ROOT / "Data" / "Graphs" / "Metrics_noisy_sweep" / timestamp
    out_dir.mkdir(parents=True, exist_ok=True)
    print(f"Output folder: {out_dir}\n")

    data = load_all_data()
    test_pos   = data["clean_test"]
    neg_traces = data["neg_traces"]
    neg_modes  = data["neg_modes"]

    # Save config immediately so it exists even if the run fails partway through
    print("=== Config ===")
    save_config(out_dir, data)

    print(f"\nSweeping {len(NOISE_LEVELS)} noise levels x "
          f"{len(METHODS)} methods\n")

    log = {
        "timestamp":    timestamp,
        "tag_k":        TAG_K,
        "n_train":      N_TRAIN,
        "n_test":       len(test_pos),
        "n_neg":        len(neg_traces),
        "noise_levels": NOISE_LEVELS,
        "f1_threshold": F1_THRESHOLD,
        "clean_noise":  CONFIG["clean"]["noise_std"],
        "noisy_noise":  CONFIG["noisy"]["noise_std"],
        "results":      [],
    }

    results_by_method = {
        m: {"precision": [], "recall": [], "f1": []}
        for m, _ in METHODS
    }

    for noise in NOISE_LEVELS:
        print(f"--- noise_std = {noise:.3f} ---")

        train_traces = generate_trace_set(
            n_traces      = N_TRAIN,
            seed          = CONFIG["seed_clean"],
            base_temp     = CONFIG["clean"]["base_temp"],
            amplitude     = CONFIG["clean"]["amplitude"],
            base_temp_std = CONFIG["clean"]["base_temp_std"],
            amplitude_std = CONFIG["clean"]["amplitude_std"],
            phase_std_h   = CONFIG["clean"]["phase_std_h"],
            noise_std     = noise,
        )

        for method, params in METHODS:
            result = run_pipeline(
                method          = method,
                params          = params,
                train_traces    = train_traces,
                test_pos_traces = test_pos,
                test_neg_traces = neg_traces,
                tag_k           = TAG_K,
                neg_modes       = neg_modes,
            )
            ov = result["overall"]
            print(f"  {method:8s}  P={ov['precision']:.3f}  "
                  f"R={ov['recall']:.3f}  F1={ov['f1']:.3f}")

            results_by_method[method]["precision"].append(ov["precision"])
            results_by_method[method]["recall"].append(ov["recall"])
            results_by_method[method]["f1"].append(ov["f1"])

            log["results"].append({
                "noise_std": noise,
                "method":    method,
                "params":    params,
                "n_states":  result["n_states"],
                "overall":   {k: v for k, v in ov.items()
                              if not isinstance(v, list)},
                "per_mode":  result["per_mode"],
            })

        with open(out_dir / "results.json", "w") as f:
            json.dump(log, f, indent=2)
        print()

    # --- Threshold analysis --------------------------------------------------
    print(f"Noise tolerance thresholds (F1 drops below {F1_THRESHOLD}):")
    threshold_log = {}
    for method in results_by_method:
        crossing, last_above = _find_threshold_crossings(
            NOISE_LEVELS,
            results_by_method[method]["f1"],
            F1_THRESHOLD,
        )
        threshold_log[method] = {
            "drops_below_at": crossing,
            "last_above":     last_above,
        }
        if crossing:
            print(f"  {method:8s}: drops below {F1_THRESHOLD} "
                  f"at noise_std={crossing} "
                  f"(last acceptable: {last_above})")
        else:
            print(f"  {method:8s}: stays above {F1_THRESHOLD} "
                  f"across all tested noise levels")

    log["threshold_analysis"] = threshold_log
    with open(out_dir / "results.json", "w") as f:
        json.dump(log, f, indent=2)

    # --- Plots ---------------------------------------------------------------
    for metric, ylabel, title in [
        ("f1",        "F1",        "F1 vs training noise"),
        ("recall",    "Recall",    "Recall vs training noise"),
        ("precision", "Precision", "Precision vs training noise"),
    ]:
        _plot_metric(
            results_by_method, NOISE_LEVELS,
            metric, ylabel, title, F1_THRESHOLD,
            out_dir / f"{metric}_vs_noise.png",
            )

    print(f"\nDone. Results -> {out_dir}")