"""
exp_53_noise_sweep.py
=====================
Experiment 5.3 — Noise tolerance threshold.

Gradually increases training noise level and records F1 per method.
Answers "how noisy is too noisy?" with a principled threshold rather
than just two snapshots (Experiments 5.1 and 5.2).

Unlike other experiments, training data MUST be generated at each noise
level — that is the experiment. The test set and negatives are loaded
from disk (generated by generate_all_data.py) so they are identical
across all experiments.

Requires: run generate_all_data.py first.

Output (timestamped folder under Graphs/exp_53/):
  results.json        — all metrics per noise level per method
  f1_vs_noise.png
  recall_vs_noise.png
  precision_vs_noise.png
"""

import json
import sys
from datetime import datetime
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

# Script lives at src/2-Synthetic_section/exp_53_noise_sweep.py
# ROOT = CPS---Timed-automata/
ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from Generate_data import load_all_data, CONFIG
from Generators import generate_trace_set, NEG_MODE_NAMES
from Pipeline import run_pipeline


# =============================================================================
# CONFIG
# =============================================================================

# Training set size for the sweep.
# Keep consistent with generate_all_data.py CONFIG["n_train"] unless
# you deliberately want a different training size here.
N_TRAIN = CONFIG["n_train"]

# Noise levels to sweep (noise_std in °C)
# Starts below the clean level from generate_all_data.py and goes well
# above the noisy level so the full degradation curve is visible.
NOISE_LEVELS = [0.02, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.4, 0.5, 0.7, 1.0]

# F1 below this is considered unacceptable — used for threshold annotation
F1_THRESHOLD = 0.7

TAG_K = 2

METHODS = [
    ("naive",   {"bins": 15}),
    ("sax",     {"w": 288, "bins": 15}),
    ("persist", {"bins": 15}),
]

METHOD_COLORS = {
    "naive":   "steelblue",
    "sax":     "darkorange",
    "persist": "seagreen",
}


# =============================================================================
# PLOTTING
# =============================================================================

def _plot_metric(results_by_method, noise_levels, metric, ylabel, title,
                 threshold, out_path):
    fig, ax = plt.subplots(figsize=(10, 5))

    for method, vals in results_by_method.items():
        ax.plot(noise_levels, vals[metric],
                marker="o", linewidth=2, markersize=5,
                color=METHOD_COLORS.get(method, "gray"),
                label=method)

    ax.axhline(threshold, color="red", linewidth=1.2, linestyle="--",
               label=f"Threshold = {threshold}")

    # Annotate the clean and noisy levels from generate_all_data.py
    # so readers can see where Exp 5.1 and 5.2 sit on the curve
    clean_noise = CONFIG["clean"]["noise_std"]
    noisy_noise = CONFIG["noisy"]["noise_std"]
    for level, label_text in [(clean_noise, "clean (Exp 5.1)"),
                              (noisy_noise, "noisy (Exp 5.2)")]:
        ax.axvline(level, color="gray", linewidth=1.0, linestyle=":",
                   alpha=0.7)
        ax.text(level, 0.02, label_text, rotation=90,
                fontsize=7, color="gray", va="bottom", ha="right")

    ax.set_xlabel("Training noise std (°C)")
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.legend()
    ax.grid(True, linestyle="--", alpha=0.5)
    ax.set_ylim(0, 1.05)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {out_path}")


def _find_threshold_crossings(noise_levels, f1_vals, threshold):
    """
    Return the first noise level where F1 drops below threshold.
    Also returns the last level where it was still above threshold.
    """
    crossing_at    = None
    last_above     = None
    for n, f in zip(noise_levels, f1_vals):
        if f >= threshold:
            last_above = n
        elif crossing_at is None:
            crossing_at = n
    return crossing_at, last_above


# =============================================================================
# MAIN
# =============================================================================

if __name__ == "__main__":
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    out_dir   = ROOT / "Data" / "Graphs" / "Metrics_noisy_sweep" / timestamp
    out_dir.mkdir(parents=True, exist_ok=True)
    print(f"Output folder: {out_dir}\n")

    # --- Load fixed test set and negatives from disk -------------------------
    # Using the centrally generated data ensures the test conditions are
    # identical to Experiments 5.1 and 5.2, making results comparable.
    data = load_all_data()
    test_pos   = data["clean_test"]
    neg_traces = data["neg_traces"]
    neg_modes  = data["neg_modes"]

    print(f"\nSweeping {len(NOISE_LEVELS)} noise levels x "
          f"{len(METHODS)} methods\n")

    log = {
        "timestamp":    timestamp,
        "tag_k":        TAG_K,
        "n_train":      N_TRAIN,
        "n_test":       len(test_pos),
        "n_neg":        len(neg_traces),
        "noise_levels": NOISE_LEVELS,
        "f1_threshold": F1_THRESHOLD,
        "clean_noise":  CONFIG["clean"]["noise_std"],
        "noisy_noise":  CONFIG["noisy"]["noise_std"],
        "results":      [],
    }

    # {method: {metric: [val_per_noise_level]}}
    results_by_method = {
        m: {"precision": [], "recall": [], "f1": []}
        for m, _ in METHODS
    }

    for noise in NOISE_LEVELS:
        print(f"--- noise_std = {noise:.3f} ---")

        # Training traces are generated fresh at each noise level.
        # Base parameters match generate_all_data.py CONFIG["clean"] exactly
        # except noise_std is overridden by the sweep.
        train_traces = generate_trace_set(
            n_traces      = N_TRAIN,
            seed          = CONFIG["seed_clean"],
            base_temp     = CONFIG["clean"]["base_temp"],
            amplitude     = CONFIG["clean"]["amplitude"],
            base_temp_std = CONFIG["clean"]["base_temp_std"],
            amplitude_std = CONFIG["clean"]["amplitude_std"],
            phase_std_h   = CONFIG["clean"]["phase_std_h"],
            noise_std     = noise,                           # ← swept
        )

        for method, params in METHODS:
            result = run_pipeline(
                method          = method,
                params          = params,
                train_traces    = train_traces,
                test_pos_traces = test_pos,
                test_neg_traces = neg_traces,
                tag_k           = TAG_K,
                neg_modes       = neg_modes,
            )
            ov = result["overall"]
            print(f"  {method:8s}  P={ov['precision']:.3f}  "
                  f"R={ov['recall']:.3f}  F1={ov['f1']:.3f}")

            results_by_method[method]["precision"].append(ov["precision"])
            results_by_method[method]["recall"].append(ov["recall"])
            results_by_method[method]["f1"].append(ov["f1"])

            log["results"].append({
                "noise_std": noise,
                "method":    method,
                "params":    params,
                "n_states":  result["n_states"],
                "overall":   {k: v for k, v in ov.items()
                              if not isinstance(v, list)},
                "per_mode":  result["per_mode"],
            })

        # Save after every noise level so partial runs are recoverable
        with open(out_dir / "results.json", "w") as f:
            json.dump(log, f, indent=2)
        print()

    # --- Threshold analysis --------------------------------------------------
    print(f"Noise tolerance thresholds (F1 drops below {F1_THRESHOLD}):")
    threshold_log = {}
    for method in results_by_method:
        crossing, last_above = _find_threshold_crossings(
            NOISE_LEVELS,
            results_by_method[method]["f1"],
            F1_THRESHOLD,
        )
        threshold_log[method] = {
            "drops_below_at": crossing,
            "last_above":     last_above,
        }
        if crossing:
            print(f"  {method:8s}: drops below {F1_THRESHOLD} "
                  f"at noise_std={crossing} "
                  f"(last acceptable: {last_above})")
        else:
            print(f"  {method:8s}: stays above {F1_THRESHOLD} "
                  f"across all tested noise levels")

    log["threshold_analysis"] = threshold_log
    with open(out_dir / "results.json", "w") as f:
        json.dump(log, f, indent=2)

    # --- Plots ---------------------------------------------------------------
    for metric, ylabel, title in [
        ("f1",        "F1",        "F1 vs training noise (Exp 5.3)"),
        ("recall",    "Recall",    "Recall vs training noise (Exp 5.3)"),
        ("precision", "Precision", "Precision vs training noise (Exp 5.3)"),
    ]:
        _plot_metric(
            results_by_method, NOISE_LEVELS,
            metric, ylabel, title, F1_THRESHOLD,
            out_dir / f"{metric}_vs_noise.png",
            )

    print(f"\nDone. Results -> {out_dir}")